import { db } from './schema'

const SEED_VERSION = 2

const now = () => new Date().toISOString()

const SEED_RECIPES = [
  /* ═══════════════════════ ALLTAG ═══════════════════════ */

  {
    id: 'bolognese-basis',
    name: 'Bolognese-Basis (Thermomix)',
    category: 'mealprep',
    cuisine: 'italienisch',
    time_min: 75,
    portions: 8,
    valerie_tauglich: true,
    device: ['thermomix'],
    seasonal: null,
    ingredients: [
      { name: 'Rinderhack (Bio)', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Schweinehack', amount: '200', unit: 'g', pantry_basic: false },
      { name: 'Karotte', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Sellerie', amount: '1', unit: 'Stange', pantry_basic: false },
      { name: 'Zwiebel', amount: '1', unit: 'Stück', pantry_basic: true },
      { name: 'Knoblauch', amount: '3', unit: 'Zehen', pantry_basic: true },
      { name: 'Olivenöl', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Dosentomaten (gehackt)', amount: '800', unit: 'g', pantry_basic: true },
      { name: 'Rotwein', amount: '200', unit: 'ml', pantry_basic: false },
      { name: 'Tomatenmark', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Lorbeerblatt, Oregano, Salz, Pfeffer', amount: '', unit: '', pantry_basic: true },
      { name: 'Milch', amount: '50', unit: 'ml', pantry_basic: false },
    ],
    steps: [
      'Sellerie, Karotte, Zwiebel, Knoblauch in den Thermomix, 5 Sek / Stufe 5 zerkleinern.',
      'Olivenöl dazu, 5 min / 120°C / Stufe 1 andünsten.',
      'Hack + Tomatenmark + Gewürze zugeben, 8 min / 100°C / Linkslauf / Stufe 1 anbraten.',
      'Rotwein dazu, 5 min / Varoma / Linkslauf / Stufe 1 reduzieren.',
      'Dosentomaten + Milch + Lorbeerblatt rein, 60 min / 95°C / Linkslauf / Stufe 1 simmern.',
      'Abschmecken. Mit Tagliatelle oder Rigatoni servieren.',
      'Portionieren: 2 Portionen heute, 2 Portionen Di (Tupper), Rest in XL-Silikon-Cubes einfrieren.',
    ],
    notes: 'Dauerbrenner. Die Basis ergibt Cubes für Lasagne, Moussaka-Start, Chili, gefüllte Paprika.\n\nValerie: Vor Pfeffer und starken Gewürzen 1 Schöpfer abnehmen – mild, nur Tomate + Hack. Parmesan drauf, fertig.',
  },

  {
    id: 'aglio-e-olio',
    name: 'Pasta Aglio e Olio',
    category: 'schnell',
    cuisine: 'italienisch',
    time_min: 15,
    portions: 3,
    valerie_tauglich: true,
    device: ['pfanne', 'topf'],
    seasonal: null,
    ingredients: [
      { name: 'Spaghetti (Bio)', amount: '300', unit: 'g', pantry_basic: true },
      { name: 'Knoblauch', amount: '6', unit: 'Zehen', pantry_basic: true },
      { name: 'Getrocknete Chili oder Chiliflocken', amount: '1', unit: 'TL', pantry_basic: true },
      { name: 'Olivenöl extra vergine', amount: '80', unit: 'ml', pantry_basic: true },
      { name: 'Petersilie', amount: '1', unit: 'Bund', pantry_basic: false },
      { name: 'Parmesan', amount: '', unit: 'nach Geschmack', pantry_basic: true },
    ],
    steps: [
      'Spaghetti in reichlich Salzwasser al dente kochen. Einen Becher Nudelwasser aufheben.',
      'Olivenöl in großer Pfanne auf mittlerer Hitze. Knoblauch in Scheiben + Chili zugeben und 4–5 min langsam goldbraun werden lassen (nicht verbrennen!).',
      'Nudeln abgießen, direkt in die Pfanne. Schuss Nudelwasser dazu, kurz schwenken bis cremig.',
      'Petersilie rein, Parmesan drüber, servieren.',
    ],
    notes: 'Klassischer Stress-Notfall. Alles was du brauchst ist immer da.\n\nValerie: Knoblauch + Chili weglassen. Olivenöl + Spaghetti + Parmesan – sie liebt "Butternudeln". Gurke + Tomate dazu.',
  },

  {
    id: 'shakshuka',
    name: 'Shakshuka',
    category: 'schnell',
    cuisine: 'levante',
    time_min: 25,
    portions: 3,
    valerie_tauglich: true,
    device: ['pfanne'],
    seasonal: null,
    ingredients: [
      { name: 'Paprika rot', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Zwiebel', amount: '1', unit: 'Stück', pantry_basic: true },
      { name: 'Knoblauch', amount: '3', unit: 'Zehen', pantry_basic: true },
      { name: 'Olivenöl', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Kreuzkümmel, Paprika edelsüß, Paprika scharf', amount: '', unit: '', pantry_basic: true },
      { name: 'Dosentomaten (gehackt)', amount: '400', unit: 'g', pantry_basic: true },
      { name: 'Eier', amount: '5', unit: 'Stück', pantry_basic: true },
      { name: 'Feta', amount: '100', unit: 'g', pantry_basic: false },
      { name: 'Petersilie oder Koriander', amount: '1/2', unit: 'Bund', pantry_basic: false },
      { name: 'Fladenbrot', amount: '', unit: 'zum Dippen', pantry_basic: false },
    ],
    steps: [
      'Olivenöl in Pfanne. Zwiebel + Paprika 8 min anbraten bis weich.',
      'Knoblauch + Gewürze rein, 1 min mitbraten.',
      'Tomaten + Prise Zucker + Salz dazu, 8 min köcheln bis sämig.',
      'Mit Löffel 5 Mulden in die Sauce drücken, in jede ein Ei schlagen.',
      'Deckel drauf, 5–7 min bei mittlerer Hitze – Eiweiß fest, Eigelb weich.',
      'Feta zerbröseln, Kräuter drüber. Mit Fladenbrot servieren.',
    ],
    notes: 'Abends als schnelle Brotzeit-Plus. Reste: Tomatensauce für morgen als Pasta-Basis.\n\nValerie: Kleine Portion Tomatensauce vor dem Chili abnehmen. Für sie ein separates Spiegelei. Sie tunkt Brot in die milde Sauce.',
  },

  {
    id: 'thai-erdnussnudeln',
    name: 'Thai-Erdnussnudeln',
    category: 'schnell',
    cuisine: 'thailaendisch',
    time_min: 20,
    portions: 3,
    valerie_tauglich: true,
    device: ['pfanne', 'wok', 'topf'],
    seasonal: null,
    ingredients: [
      { name: 'Reisnudeln (flach, Pad-Thai-Style)', amount: '300', unit: 'g', pantry_basic: true },
      { name: 'Hähnchenbrust oder Tofu', amount: '200', unit: 'g', pantry_basic: false },
      { name: 'Karotte', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Paprika', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Edamame (TK)', amount: '1', unit: 'Handvoll', pantry_basic: false },
      { name: 'Lauchzwiebeln', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Erdnüsse (geröstet)', amount: '1', unit: 'Handvoll', pantry_basic: true },
      { name: 'Erdnussbutter', amount: '4', unit: 'EL', pantry_basic: true },
      { name: 'Sojasauce', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Reisessig', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Honig', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Sesamöl + Limette + Ingwer', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Reisnudeln nach Packung einweichen (meist heißes Wasser 8 min).',
      'Sauce: Erdnussbutter + Sojasauce + Reisessig + Honig + Sesamöl + Limettensaft + geriebener Ingwer + Chili + 3 EL heißes Wasser glatt rühren.',
      'Hähnchen/Tofu in Pfanne 6 min anbraten. Rausnehmen.',
      'Karotte (Julienne) + Paprika + Edamame 3 min anbraten (noch knackig).',
      'Nudeln + Fleisch wieder dazu, Sauce drüber, gut vermischen.',
      'Mit Limette, Lauchzwiebel, Erdnüssen servieren.',
    ],
    notes: 'Erdnuss-Sauce hält 3 Tage – Reste als Dip für Gemüsesticks.\n\nValerie: Nudeln + geraspelte Karotte + ein paar Erdnüsse + milde Sauce (ohne Chili, mehr Erdnussbutter + Honig). Sie liebt\'s.',
  },

  {
    id: 'teriyaki-bowl',
    name: 'Teriyaki-Hähnchen-Bowl',
    category: 'schnell',
    cuisine: 'japanisch',
    time_min: 25,
    portions: 3,
    valerie_tauglich: true,
    device: ['pfanne'],
    seasonal: null,
    ingredients: [
      { name: 'Hähnchenschenkel ohne Knochen', amount: '400', unit: 'g', pantry_basic: false },
      { name: 'Sushi-Reis oder Basmati', amount: '250', unit: 'g', pantry_basic: true },
      { name: 'Gurke', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Edamame (TK)', amount: '100', unit: 'g', pantry_basic: false },
      { name: 'Lauchzwiebel', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Sesam', amount: '', unit: '', pantry_basic: true },
      { name: 'Sojasauce', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Mirin', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Sake oder trockener Sherry', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Zucker', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Ingwer', amount: '1', unit: 'TL (gerieben)', pantry_basic: true },
    ],
    steps: [
      'Reis waschen, nach Packung kochen.',
      'Teriyaki-Zutaten in kleiner Schüssel mischen.',
      'Hähnchen in Pfanne hautseitig 6 min bei mittlerer Hitze goldbraun. Wenden, weitere 4 min.',
      'Fett abgießen. Teriyaki-Sauce dazu, 2–3 min einkochen bis glasiert. Hähnchen in Streifen schneiden.',
      'Bowl bauen: Reis, Hähnchen, Gurke, Edamame. Sauce drüber, Sesam + Lauchzwiebel.',
    ],
    notes: 'Teriyaki-Sauce auf Vorrat machen (3× Menge) – hält 2 Wochen.\n\nValerie: Hähnchen-Stücke vor der Sauce abnehmen (pur mit Mini-Sojasauce zum Dippen). Reis + Gurke + Edamame. Sie isst das zu 100%.',
  },

  {
    id: 'korean-beef-bowl',
    name: 'Korean Beef Bowl',
    category: 'schnell',
    cuisine: 'koreanisch',
    time_min: 20,
    portions: 3,
    valerie_tauglich: true,
    device: ['pfanne'],
    seasonal: null,
    ingredients: [
      { name: 'Rinderhack', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Knoblauch', amount: '3', unit: 'Zehen', pantry_basic: true },
      { name: 'Ingwer', amount: '2', unit: 'cm', pantry_basic: true },
      { name: 'Sojasauce', amount: '4', unit: 'EL', pantry_basic: true },
      { name: 'Sesamöl', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Brauner Zucker', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Gochujang (koreanische Chilipaste)', amount: '1', unit: 'TL (optional)', pantry_basic: true },
      { name: 'Reis', amount: '250', unit: 'g', pantry_basic: true },
      { name: 'Karotte', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Gurke', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Lauchzwiebeln', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Sesam + Kimchi (gekauft)', amount: '', unit: '', pantry_basic: false },
    ],
    steps: [
      'Reis kochen.',
      'Hack in trockener Pfanne krümelig braten, Fett abgießen.',
      'Knoblauch (gepresst) + Ingwer (gerieben) 30 Sek. mitbraten.',
      'Sojasauce + Zucker + Sesamöl (+ optional Gochujang) rein, 2 min einkochen.',
      'Bowl: Reis, Hack, Karotte (geraspelt), Gurke (in Stiften), Lauchzwiebel, Sesam. Kimchi separat.',
    ],
    notes: 'Rest kalt in Salatblätter gewickelt (koreanisches Ssam) ist phänomenal.\n\nValerie: Teil des Hacks vor Gochujang abnehmen. Reis + mildes Hack + Gurke + geraspelte Karotte. Kimchi nicht für sie.',
  },

  {
    id: 'linsen-dal',
    name: 'Linsen-Dal',
    category: 'mealprep',
    cuisine: 'indisch',
    time_min: 30,
    portions: 4,
    valerie_tauglich: true,
    device: ['topf'],
    seasonal: null,
    ingredients: [
      { name: 'Rote Linsen', amount: '250', unit: 'g', pantry_basic: true },
      { name: 'Zwiebel', amount: '1', unit: 'Stück', pantry_basic: true },
      { name: 'Knoblauch', amount: '3', unit: 'Zehen', pantry_basic: true },
      { name: 'Ingwer', amount: '2', unit: 'cm', pantry_basic: true },
      { name: 'Kokosmilch', amount: '400', unit: 'ml', pantry_basic: true },
      { name: 'Dosentomaten', amount: '400', unit: 'g', pantry_basic: true },
      { name: 'Kurkuma, Kreuzkümmel (ganz), Garam Masala, Chili', amount: '', unit: '', pantry_basic: true },
      { name: 'Gemüsebrühe', amount: '500', unit: 'ml', pantry_basic: true },
      { name: 'Zitronensaft', amount: '1/2', unit: 'Zitrone', pantry_basic: false },
      { name: 'Koriander', amount: '1/2', unit: 'Bund', pantry_basic: false },
      { name: 'Basmati-Reis', amount: '', unit: 'als Beilage', pantry_basic: true },
    ],
    steps: [
      'Linsen abspülen. Zwiebel, Knoblauch, Ingwer fein hacken.',
      'In Topf Öl erhitzen, Kreuzkümmelsamen kurz rösten.',
      'Zwiebel + Knoblauch + Ingwer 5 min anbraten.',
      'Kurkuma + Garam Masala + Chili rein, 30 Sek.',
      'Tomaten + Linsen + Kokosmilch + Brühe dazu. Aufkochen, 20 min leise simmern bis Linsen zerfallen.',
      'Mit Zitrone + Salz abschmecken. Mit Koriander + Reis servieren.',
    ],
    notes: 'Klassischer Mealprep-Kandidat. Hält 3 Tage, gefriert perfekt als Cube.\n\nValerie: Vor dem Chili eine Portion abnehmen. Milder Dal + Reis + Joghurt-Klecks. Sie mag\'s überraschend gern.',
  },

  {
    id: 'miso-lachs',
    name: 'Miso-Lachs aus dem Ofen',
    category: 'schnell',
    cuisine: 'japanisch',
    time_min: 27,
    portions: 3,
    valerie_tauglich: true,
    device: ['ofen'],
    seasonal: null,
    ingredients: [
      { name: 'Lachsfilets (mit Haut)', amount: '3', unit: 'à 150 g', pantry_basic: false },
      { name: 'Weißes Miso (Shiro)', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Mirin', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Sake', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Honig', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Reis', amount: '250', unit: 'g', pantry_basic: true },
      { name: 'Pak Choi oder Spinat', amount: '1', unit: 'Bund', pantry_basic: false },
      { name: 'Sesam + Lauchzwiebel', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Miso + Mirin + Sake + Honig glatt rühren. Lachs einstreichen (idealerweise 30 min ziehen lassen, geht aber auch sofort).',
      'Ofen auf 200°C Ober-/Unterhitze vorheizen. Reis kochen.',
      'Lachs auf Backpapier, 12 min backen (medium) oder 15 min durchgegart.',
      'Pak Choi halbieren, in Pfanne mit Sesamöl + Sojasauce 4 min dämpfen.',
      'Anrichten: Reis, Lachs, Pak Choi, Sesam, Lauchzwiebel.',
    ],
    notes: '1× Fisch pro Woche ist Ziel – der einfachste Weg. Miso hält ewig im Kühlschrank.\n\nValerie: Ein Stückchen Lachs ohne Marinade in einem Extra-Eck mitbacken. Reis + Gurke als Beilage.',
  },

  {
    id: 'caprese-quinoa-bowl',
    name: 'Caprese-Quinoa-Bowl',
    category: 'schnell',
    cuisine: 'mediterran',
    time_min: 20,
    portions: 3,
    valerie_tauglich: true,
    device: ['topf'],
    seasonal: null,
    ingredients: [
      { name: 'Quinoa', amount: '200', unit: 'g', pantry_basic: true },
      { name: 'Gemüsebrühe', amount: '400', unit: 'ml', pantry_basic: true },
      { name: 'Cherrytomaten', amount: '300', unit: 'g', pantry_basic: false },
      { name: 'Mozzarella (Büffel)', amount: '250', unit: 'g', pantry_basic: false },
      { name: 'Basilikum', amount: '1', unit: 'Bund', pantry_basic: false },
      { name: 'Olivenöl', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Balsamico oder Balsamico-Creme', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Pinienkerne (optional)', amount: '', unit: 'geröstet', pantry_basic: true },
    ],
    steps: [
      'Quinoa waschen, in Brühe 15 min mit Deckel köcheln bis alles aufgenommen. Abkühlen.',
      'Tomaten halbieren, Mozzarella würfeln, Basilikum grob zerrupfen.',
      'Alles in Schüssel, Olivenöl + Balsamico + Salz + Pfeffer, vermischen.',
      'Pinienkerne drüber.',
    ],
    notes: 'Geht auch morgen kalt aus dem Kühlschrank – wird sogar besser.\n\nValerie: Isst das wahrscheinlich 1:1 mit. Falls nicht: Tomaten + Mozzarella pur, Quinoa extra Schälchen.',
  },

  {
    id: 'hummus-falafel',
    name: 'Hummus-Bowl mit Falafel',
    category: 'schnell',
    cuisine: 'levante',
    time_min: 20,
    portions: 3,
    valerie_tauglich: true,
    device: ['pfanne', 'thermomix'],
    seasonal: null,
    ingredients: [
      { name: 'Falafel (gekauft oder TK)', amount: '12', unit: 'Stück', pantry_basic: false },
      { name: 'Hummus (gekauft oder selbst)', amount: '250', unit: 'g', pantry_basic: false },
      { name: 'Gurke', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Tomaten', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Rotkohl', amount: '1/2', unit: 'Stück', pantry_basic: false },
      { name: 'Petersilie', amount: '1', unit: 'Bund', pantry_basic: false },
      { name: 'Tahini', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Zitronensaft', amount: '1', unit: 'Zitrone', pantry_basic: false },
      { name: 'Fladenbrot oder Pita', amount: '', unit: '', pantry_basic: false },
    ],
    steps: [
      'Falafel erwärmen (Pfanne mit Öl 6 min oder Ofen 200°C 10 min).',
      'Tahini-Dressing: 3 EL Tahini + Saft 1 Zitrone + 1 Knoblauchzehe + 4 EL Wasser + Salz verquirlen.',
      'Bowl: Hummus auf Teller streichen, Falafel drauflegen, Gurke (Stifte), Tomate (gewürfelt), Rotkohl (fein gehobelt), Petersilie. Dressing drüber. Pita dazu.',
      'Eigener Hummus (Thermomix): 1 Dose Kichererbsen + 3 EL Tahini + Saft 1 Zitrone + 2 Knoblauchzehen + 100 ml Aquafaba + Salz → 60 Sek / Stufe 8.',
    ],
    notes: 'Hummus auf Vorrat machen – hält 5 Tage. Tolle Snack-Basis.\n\nValerie: Falafel pur (sie liebt sie), Gurke + Tomate separat, Pita-Stücke. Hummus zum Tunken, Tahini-Dressing weglassen (zu intensiv).',
  },

  {
    id: 'overnight-oats',
    name: 'Overnight Oats (5-Portionen-Basis)',
    category: 'fruehstueck',
    cuisine: 'fusion',
    time_min: 10,
    portions: 5,
    valerie_tauglich: true,
    device: ['thermomix'],
    seasonal: null,
    ingredients: [
      { name: 'Zarte Haferflocken', amount: '300', unit: 'g', pantry_basic: true },
      { name: 'Hafermilch oder Vollmilch', amount: '600', unit: 'ml', pantry_basic: true },
      { name: 'Naturjoghurt', amount: '400', unit: 'g', pantry_basic: false },
      { name: 'Chiasamen', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Ahornsirup', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Vanille', amount: '1', unit: 'TL', pantry_basic: true },
      { name: 'Prise Salz', amount: '', unit: '', pantry_basic: true },
      { name: 'Topping: Obst, Nüsse, Leinsamen', amount: '', unit: 'saisonal', pantry_basic: false },
    ],
    steps: [
      'Alle Basis-Zutaten in Thermomix, 15 Sek / Stufe 2 verrühren.',
      'Auf 5 Weck-Gläser (290 ml) verteilen.',
      'Über Nacht in den Kühlschrank.',
      'Morgens: Obst (Erdbeeren, Banane, Heidelbeeren, Apfel) + Nüsse drauf.',
    ],
    notes: 'Sonntag abends ist die Standard-Routine. Anna macht das meistens. Hält 5 Tage – danach wird\'s pampig.\n\nValerie: 1:1-Anteil mit etwas mehr Ahornsirup + Banane in Scheiben oben drauf. Sie liebt\'s.',
  },

  {
    id: 'maki-rollen',
    name: 'Maki-Rollen einfach',
    category: 'schnell',
    cuisine: 'japanisch',
    time_min: 30,
    portions: 3,
    valerie_tauglich: true,
    device: ['topf'],
    seasonal: null,
    ingredients: [
      { name: 'Sushi-Reis', amount: '300', unit: 'g', pantry_basic: true },
      { name: 'Reisessig', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Zucker', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Salz', amount: '1', unit: 'TL', pantry_basic: true },
      { name: 'Nori-Blätter', amount: '4', unit: 'Stück', pantry_basic: true },
      { name: 'Gurke', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Avocado', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Lachs (Sushi-Qualität) oder Räucherlachs', amount: '200', unit: 'g', pantry_basic: false },
      { name: 'Sojasauce, Wasabi, eingelegter Ingwer', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Reis gründlich waschen (bis Wasser klar). In Topf mit gleicher Menge Wasser. Aufkochen, dann 15 min auf kleinster Stufe mit Deckel. 10 min ziehen lassen.',
      'Sushi-Essig (Reisessig + Zucker + Salz) unter den warmen Reis mischen, abkühlen lassen.',
      'Nori-Blatt auf Rollmatte, glänzende Seite unten. Reis dünn verteilen, 2 cm am oberen Rand freilassen.',
      'Füllung (Gurke + Avocado + Lachs) als Streifen auf das untere Drittel legen.',
      'Von unten mit Rollmatte fest einrollen, oberen Rand leicht anfeuchten zum Verschließen.',
      'Mit scharfem Messer in 8 Stücke schneiden (Messer zwischendurch abwischen).',
    ],
    notes: 'Wochenend-Projekt, aber immer ein Erlebnis. Mit Valerie zusammen machen – sie darf rollen.\n\nValerie: Reis + Gurke + Lachs separat als "Sushi-Bowl". Die Rollen sind ihr oft zu fummelig. Reis mit Sojasauce zum Tunken = Hit.',
  },

  /* ═══════════════════════ MITTEL ═══════════════════════ */

  {
    id: 'rotes-thai-curry',
    name: 'Rotes Thai Curry',
    category: 'mealprep',
    cuisine: 'thailaendisch',
    time_min: 40,
    portions: 4,
    valerie_tauglich: true,
    device: ['wok', 'pfanne'],
    seasonal: null,
    ingredients: [
      { name: 'Rote Currypaste (Mae Ploy)', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Kokosmilch', amount: '400', unit: 'ml', pantry_basic: true },
      { name: 'Hühnerbrühe', amount: '200', unit: 'ml', pantry_basic: true },
      { name: 'Hähnchenbrust oder Tofu', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Paprika', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Bambussprossen (Dose)', amount: '100', unit: 'g', pantry_basic: true },
      { name: 'Zucchini', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Fischsauce', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Palmzucker oder brauner Zucker', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Limette', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Thai-Basilikum', amount: '', unit: 'nach Geschmack', pantry_basic: false },
      { name: 'Reis', amount: '', unit: 'als Beilage', pantry_basic: true },
    ],
    steps: [
      'Reis kochen.',
      '1 EL Kokosmilch (dicke Schicht oben!) in Wok, Currypaste dazu, 3 min rösten bis intensiv duftend (wichtig!).',
      'Rest Kokosmilch + Brühe dazu, aufkochen.',
      'Hähnchen/Tofu rein, 8 min ziehen lassen.',
      'Paprika + Bambus + Zucchini, 5 min köcheln.',
      'Fischsauce + Palmzucker + Limette abschmecken.',
      'Basilikum drüber, mit Reis servieren.',
    ],
    notes: 'Gelbes/grünes Curry mit gleicher Methode, andere Paste. Currypasten halten monatelang.\n\nValerie: Vor der Currypaste ein kleines Stück Hähnchen in normaler Kokosmilch separat garen. Reis + Hähnchen + Gurke/Paprika-Rohkost.',
  },

  {
    id: 'haehnchen-shawarma',
    name: 'Hähnchen-Shawarma-Bowl',
    category: 'mealprep',
    cuisine: 'levante',
    time_min: 45,
    portions: 3,
    valerie_tauglich: true,
    device: ['plancha', 'pfanne'],
    seasonal: null,
    ingredients: [
      { name: 'Hähnchenschenkel ohne Knochen', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Basmati-Reis', amount: '250', unit: 'g', pantry_basic: true },
      { name: 'Olivenöl', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Kreuzkümmel, Koriander, Paprika edelsüß, Zimt, Kurkuma', amount: '', unit: 'je 1-2 TL', pantry_basic: true },
      { name: 'Knoblauch', amount: '3', unit: 'Zehen', pantry_basic: true },
      { name: 'Zitrone', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Salatherzen', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Tomaten', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Gurke', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Rote Zwiebel', amount: '1/2', unit: 'Stück', pantry_basic: false },
      { name: 'Petersilie, Tahini, Oliven', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Marinade: Olivenöl + Gewürze + Knoblauch (gepresst) + Zitronensaft + Salz, Pfeffer mischen. Hähnchen drin wenden, mind. 20 min (besser 2h) ziehen lassen.',
      'Reis kochen.',
      'Plancha oder Pfanne heiß. Hähnchen in einer Lage scharf anbraten, je 4 min pro Seite, bis gebräunt und durch. Rausnehmen, 3 min ruhen lassen, in Streifen schneiden.',
      'Bowl bauen: Reis, Hähnchen, Salat, Tomate, Gurke, Zwiebel, Petersilie. Tahini drüber.',
    ],
    notes: 'Marinade 4-fach anrühren – Rest in den Freezer (mit Hähnchen eingefroren → Direkt-Gefrier-zum-Plancha-Rezept).\n\nValerie: Ein Stück Hähnchen vor der Marinade abzweigen, kurz in Butter braten. Reis + Hähnchen pur + Gurke + Tomate.',
  },

  {
    id: 'gemuese-lasagne',
    name: 'Gemüse-Lasagne',
    category: 'mealprep',
    cuisine: 'italienisch',
    time_min: 55,
    portions: 4,
    valerie_tauglich: true,
    device: ['ofen'],
    seasonal: null,
    ingredients: [
      { name: 'Lasagneplatten (ohne Vorkochen)', amount: '10', unit: 'Stück', pantry_basic: true },
      { name: 'Zucchini', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Aubergine', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Paprika', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Spinat (frisch oder TK)', amount: '200', unit: 'g', pantry_basic: false },
      { name: 'Dosentomaten', amount: '400', unit: 'g', pantry_basic: true },
      { name: 'Ricotta', amount: '250', unit: 'g', pantry_basic: false },
      { name: 'Mozzarella', amount: '200', unit: 'g', pantry_basic: false },
      { name: 'Parmesan', amount: '50', unit: 'g', pantry_basic: true },
      { name: 'Zwiebel + Knoblauch + Olivenöl + Oregano', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Ofen auf 200°C vorheizen.',
      'Zwiebel + Knoblauch anbraten, Dosentomaten + Oregano dazu, 10 min köcheln → Tomatensauce.',
      'Zucchini + Aubergine in Pfanne (oder Plancha) kurz anbraten.',
      'Spinat kurz andünsten, ausdrücken. Mit Ricotta + Prise Muskat mischen.',
      'Schichten: Sauce → Platten → Gemüse → Ricotta-Spinat → Mozzarella → wiederholen. Oberste Schicht: Sauce + Parmesan.',
      '35 min backen bis gebräunt. 5 min ruhen.',
    ],
    notes: 'Variante mit Bolognese-Cubes aus dem Freezer: halbe Bolognese / halbe Gemüse-Schicht. Dauert 5 min weniger Vorbereitung.\n\nValerie: Sie liebt Lasagne – gleiche Portion, kleiner geschnitten. Falls zu würzig: weniger Oregano in ihrer Ecke.',
  },

  {
    id: 'chicken-katsu',
    name: 'Chicken Katsu mit Tonkatsu-Sauce',
    category: 'schnell',
    cuisine: 'japanisch',
    time_min: 30,
    portions: 3,
    valerie_tauglich: true,
    device: ['pfanne'],
    seasonal: null,
    ingredients: [
      { name: 'Hähnchenbrustfilets', amount: '3', unit: 'Stück', pantry_basic: false },
      { name: 'Panko (japanisches Brotsemmelbrot)', amount: '100', unit: 'g', pantry_basic: true },
      { name: 'Eier', amount: '2', unit: 'Stück', pantry_basic: true },
      { name: 'Mehl', amount: '4', unit: 'EL', pantry_basic: true },
      { name: 'Sonnenblumenöl', amount: '', unit: 'zum Braten', pantry_basic: true },
      { name: 'Reis', amount: '250', unit: 'g', pantry_basic: true },
      { name: 'Weißkohl', amount: '1/2', unit: 'Stück', pantry_basic: false },
      { name: 'Ketchup, Worcestersauce, Sojasauce, Zucker, Senf (für Sauce)', amount: '', unit: '', pantry_basic: true },
      { name: 'Zitrone', amount: '1', unit: 'Stück', pantry_basic: false },
    ],
    steps: [
      'Reis kochen.',
      'Tonkatsu-Sauce: 4 EL Ketchup + 2 EL Worcestersauce + 2 EL Sojasauce + 1 EL Zucker + 1 TL Senf verrühren.',
      'Hähnchen auf 1,5 cm dünn klopfen. Salzen.',
      'Panade: Mehl → Ei → Panko. Gut andrücken.',
      'Öl in Pfanne (2 cm hoch), auf 170°C. Hähnchen 4 min pro Seite goldbraun.',
      'Auf Küchenpapier abtropfen, in Streifen schneiden.',
      'Servieren: Reis, Katsu, Kohl (fein gehobelt), Sauce drüber, Zitronenspalte.',
    ],
    notes: 'Katsu-Sandwich (Sando) am nächsten Tag: Toastbrot + Kohl + Katsu + Sauce = Hit.\n\nValerie: Gleiche Portion – sie liebt Panade. Sauce separat (sie taucht manchmal rein). Reis pur, Gurke/Karotte dazu.',
  },

  {
    id: 'chana-masala',
    name: 'Chana Masala',
    category: 'mealprep',
    cuisine: 'indisch',
    time_min: 35,
    portions: 4,
    valerie_tauglich: true,
    device: ['topf'],
    seasonal: null,
    ingredients: [
      { name: 'Kichererbsen (Dose)', amount: '2', unit: 'Dosen', pantry_basic: true },
      { name: 'Zwiebeln', amount: '2', unit: 'Stück', pantry_basic: true },
      { name: 'Knoblauch', amount: '4', unit: 'Zehen', pantry_basic: true },
      { name: 'Ingwer', amount: '3', unit: 'cm', pantry_basic: true },
      { name: 'Dosentomaten', amount: '400', unit: 'g', pantry_basic: true },
      { name: 'Garam Masala, Kreuzkümmel, Koriander, Kurkuma, Chili, Amchur (opt.)', amount: '', unit: '', pantry_basic: true },
      { name: 'Wasser', amount: '200', unit: 'ml', pantry_basic: true },
      { name: 'Zitronensaft', amount: '1', unit: 'EL', pantry_basic: false },
      { name: 'Frischer Koriander', amount: '1', unit: 'Bund', pantry_basic: false },
      { name: 'Basmati-Reis oder Naan', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Reis kochen / Naan vorbereiten.',
      'Öl in Topf. Zwiebeln 8 min goldbraun braten.',
      'Knoblauch + Ingwer (gerieben) dazu, 2 min.',
      'Alle Gewürze (außer Amchur) rein, 30 Sek rösten.',
      'Dosentomaten dazu, 5 min einkochen lassen bis dick.',
      'Kichererbsen + Wasser + Amchur, 15 min simmern. Einige Kichererbsen zerdrücken (macht Sauce dicker).',
      'Zitrone + Salz. Koriander drüber.',
    ],
    notes: 'Mealprep-Held. Hält 4 Tage, friert perfekt ein als Cube.\n\nValerie: Kichererbsen + milde Tomatensauce vor dem Chili abnehmen, etwas Joghurt drunter mischen. Reis dazu.',
  },

  {
    id: 'pad-thai',
    name: 'Pad Thai',
    category: 'schnell',
    cuisine: 'thailaendisch',
    time_min: 30,
    portions: 3,
    valerie_tauglich: true,
    device: ['wok'],
    seasonal: null,
    ingredients: [
      { name: 'Reisnudeln (flach, breit)', amount: '300', unit: 'g', pantry_basic: true },
      { name: 'Garnelen oder Hähnchen oder Tofu', amount: '300', unit: 'g', pantry_basic: false },
      { name: 'Eier', amount: '2', unit: 'Stück', pantry_basic: true },
      { name: 'Lauchzwiebeln', amount: '3', unit: 'Stück', pantry_basic: false },
      { name: 'Sojasprossen', amount: '100', unit: 'g', pantry_basic: false },
      { name: 'Erdnüsse (gehackt)', amount: '1', unit: 'Handvoll', pantry_basic: true },
      { name: 'Limette', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Koriander', amount: '1/2', unit: 'Bund', pantry_basic: false },
      { name: 'Tamarindenpaste', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Fischsauce', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Palmzucker + Sojasauce', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Reisnudeln 8 min in heißem Wasser einweichen, abgießen.',
      'Sauce: Tamarindenpaste + Fischsauce + Palmzucker (3 EL) + Sojasauce (1 EL) verrühren.',
      'Wok sehr heiß, 2 EL Öl. Garnelen/Hähnchen/Tofu scharf anbraten, rausnehmen.',
      'Etwas Öl dazu, Eier in der Mitte aufschlagen, verquirlen und stocken lassen.',
      'Nudeln rein, Sauce drüber, alles schwenken 2 min.',
      'Garnelen + Lauchzwiebel + Sprossen zurück dazu, 1 min durchschwenken.',
      'Mit Erdnüssen, Limette, Koriander servieren.',
    ],
    notes: 'Tamarindenpaste ist der Game Changer – im Asialaden. Ketchup-Notfallvariante ist ok, aber nicht authentisch.\n\nValerie: Portion Nudeln + Ei + Garnele vor Fischsauce abnehmen. Sojasauce stattdessen. Erdnüsse drauf.',
  },

  {
    id: 'tom-kha-gai',
    name: 'Tom Kha Gai',
    category: 'schnell',
    cuisine: 'thailaendisch',
    time_min: 35,
    portions: 4,
    valerie_tauglich: true,
    device: ['topf'],
    seasonal: null,
    ingredients: [
      { name: 'Kokosmilch', amount: '400', unit: 'ml', pantry_basic: true },
      { name: 'Hühnerbrühe', amount: '500', unit: 'ml', pantry_basic: true },
      { name: 'Hähnchenbrust', amount: '300', unit: 'g', pantry_basic: false },
      { name: 'Pilze (Champignons oder Shiitake)', amount: '200', unit: 'g', pantry_basic: false },
      { name: 'Zitronengras', amount: '3', unit: 'Stangen', pantry_basic: true },
      { name: 'Galgant oder Ingwer', amount: '5', unit: 'Scheiben', pantry_basic: true },
      { name: 'Kaffir-Limettenblätter', amount: '5', unit: 'Stück', pantry_basic: true },
      { name: 'Fischsauce', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Zucker', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Vogelaugen-Chilis', amount: '1-3', unit: 'Stück', pantry_basic: true },
      { name: 'Limetten', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Koriander + Reis', amount: '', unit: 'optional', pantry_basic: false },
    ],
    steps: [
      'Brühe + Kokosmilch + Zitronengras (angedrückt, in 5 cm Stücken) + Galgant + Limettenblätter aufkochen, 10 min ziehen lassen.',
      'Pilze + Hähnchen (in dünnen Scheiben) rein, 8 min leicht köcheln.',
      'Fischsauce + Zucker + Chili + Limettensaft. Abschmecken – sauer-salzig-süß balanciert.',
      'Koriander drüber. Zitronengras + Galgant beim Essen rausnehmen (nicht essen).',
    ],
    notes: 'Galgant und Kaffir-Blätter im Asialaden besorgen und einfrieren (halten ewig). Unterschied zu "Huhn-Kokos-Suppe".\n\nValerie: Hähnchenstücke + Pilze mit etwas Brühe vor Chili und Fischsauce abnehmen. Reis dazu.',
  },

  {
    id: 'mapo-tofu',
    name: 'Mapo Tofu',
    category: 'schnell',
    cuisine: 'chinesisch',
    time_min: 25,
    portions: 3,
    valerie_tauglich: true,
    device: ['wok', 'pfanne'],
    seasonal: null,
    ingredients: [
      { name: 'Seidentofu', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Rinderhack oder Schweinehack', amount: '250', unit: 'g', pantry_basic: false },
      { name: 'Doubanjiang (Sichuan-Bohnenpaste)', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Douchi (fermentierte schwarze Bohnen, optional)', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Knoblauch', amount: '3', unit: 'Zehen', pantry_basic: true },
      { name: 'Ingwer', amount: '2', unit: 'cm', pantry_basic: true },
      { name: 'Lauchzwiebeln', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Hühnerbrühe', amount: '300', unit: 'ml', pantry_basic: true },
      { name: 'Sojasauce', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Zucker', amount: '1', unit: 'TL', pantry_basic: true },
      { name: 'Sichuanpfeffer', amount: '1', unit: 'TL', pantry_basic: true },
      { name: 'Speisestärke', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Reis', amount: '', unit: 'als Beilage', pantry_basic: true },
    ],
    steps: [
      'Reis kochen.',
      'Tofu würfeln, in leicht gesalzenem Wasser 3 min blanchieren. Vorsichtig abgießen.',
      'Öl im Wok, Hack krümelig braten, rausnehmen.',
      'Etwas Öl dazu, Doubanjiang + Douchi 30 Sek in Öl rösten bis rot-orange.',
      'Knoblauch + Ingwer dazu, 30 Sek. Brühe + Sojasauce + Zucker dazu, aufkochen.',
      'Tofu + Hack rein, 5 min sanft köcheln (nicht rühren, nur schwenken).',
      'Stärkemischung (mit 3 EL Wasser) einrühren, 1 min binden.',
      'Sichuanpfeffer (geröstet + gemörsert) + Lauchzwiebel drüber.',
    ],
    notes: 'Doubanjiang (Pixian-Marke ist top) im Asialaden – macht den Unterschied. Ohne wird\'s "nur scharfer Tofu".\n\nValerie: Tofu + Reis pur – ohne Sauce. Optional etwas Hack mit mildem Sojasauce-Wasser. Sichuanpfeffer nicht für sie.',
  },

  {
    id: 'caponata',
    name: 'Caponata',
    category: 'mealprep',
    cuisine: 'italienisch',
    time_min: 45,
    portions: 4,
    valerie_tauglich: true,
    device: ['pfanne'],
    seasonal: null,
    ingredients: [
      { name: 'Auberginen', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Sellerie', amount: '1', unit: 'Stange', pantry_basic: false },
      { name: 'Zwiebeln', amount: '2', unit: 'Stück', pantry_basic: true },
      { name: 'Dosentomaten', amount: '400', unit: 'g', pantry_basic: true },
      { name: 'Grüne Oliven', amount: '100', unit: 'g', pantry_basic: false },
      { name: 'Kapern', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Rotweinessig', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Zucker', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Pinienkerne', amount: '30', unit: 'g', pantry_basic: true },
      { name: 'Rosinen (optional)', amount: '30', unit: 'g', pantry_basic: true },
      { name: 'Olivenöl + Basilikum', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Auberginen (in 2 cm Würfeln) in viel Olivenöl in Pfanne goldbraun braten (ca. 8 min), rausnehmen.',
      'Sellerie + Zwiebeln im selben Öl 8 min weich braten.',
      'Tomaten + Oliven + Kapern + Rosinen dazu, 10 min köcheln.',
      'Auberginen zurück.',
      'Agrodolce: Essig + Zucker in kleiner Pfanne kurz aufkochen bis sirupartig, über die Caponata. 5 min weiter köcheln.',
      'Pinienkerne anrösten, drüber.',
      'Abkühlen lassen, Basilikum drauf. Schmeckt lauwarm oder kalt am besten, am nächsten Tag noch besser.',
    ],
    notes: 'Vorrat-Held. Hält 5 Tage. Auf Brot, zu Fisch, als Pasta-Sauce (verdünnt).\n\nValerie: Für ihre Portion Essig halbieren. Mit Ciabatta und Mozzarella.',
  },

  {
    id: 'baba-ganoush-kofta',
    name: 'Baba Ganoush + Lamm-Kofta',
    category: 'wochenende',
    cuisine: 'levante',
    time_min: 60,
    portions: 3,
    valerie_tauglich: true,
    device: ['ofen', 'plancha', 'pfanne'],
    seasonal: null,
    ingredients: [
      { name: 'Auberginen (große)', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Tahini', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Knoblauch', amount: '2', unit: 'Zehen', pantry_basic: true },
      { name: 'Zitrone', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Olivenöl', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Lammhack (oder Mischhack)', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Zwiebel', amount: '1', unit: 'Stück', pantry_basic: true },
      { name: 'Petersilie', amount: '1', unit: 'Bund', pantry_basic: false },
      { name: 'Kreuzkümmel, Piment, Paprika, Zimt', amount: '', unit: 'je 1 TL / ½ TL', pantry_basic: true },
      { name: 'Holzspieße', amount: '8-10', unit: 'Stück', pantry_basic: false },
      { name: 'Fladenbrot + Joghurt + Salat', amount: '', unit: '', pantry_basic: false },
    ],
    steps: [
      'Auberginen mit Gabel einstechen. Ofen 220°C, 40 min – bis Haut schwarz und Inneres butterweich.',
      'Inzwischen Kofta: alle Zutaten (Hack + fein gehackte Zwiebel + Knoblauch + Petersilie + Gewürze) mit Händen kneten, um Spieße formen (zigarrenform).',
      'Auberginen leicht abkühlen, aufschneiden, Fruchtfleisch rausschaben. Mit Tahini + Knoblauch + Zitrone + Olivenöl mixen oder mit Gabel zerdrücken (rustikaler). Salz.',
      'Kofta in Pfanne/Plancha je 3 min pro Seite scharf anbraten.',
      'Alles anrichten: Baba Ganoush, Kofta, Joghurtsauce (Joghurt + Knoblauch + Zitrone + Minze), Salat, Fladenbrot.',
    ],
    notes: 'Baba Ganoush auf Vorrat machen. Auberginen kann man auf dem BGE rauchig grillen statt im Ofen.\n\nValerie: Kofta ohne Gewürze separat formen (nur Fleisch + Salz). Joghurt + Fladenbrot + Gurke. Baba Ganoush ist ihr oft zu rauchig.',
  },

  {
    id: 'bun-bo-nam-bo',
    name: 'Bun Bo Nam Bo',
    category: 'schnell',
    cuisine: 'vietnamesisch',
    time_min: 40,
    portions: 3,
    valerie_tauglich: true,
    device: ['pfanne', 'topf'],
    seasonal: null,
    ingredients: [
      { name: 'Reisnudeln (Vermicelli)', amount: '300', unit: 'g', pantry_basic: true },
      { name: 'Rinderfiletspitzen oder Rumpsteak', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Karotten', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Gurke', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Kopfsalat', amount: '1', unit: 'kleiner', pantry_basic: false },
      { name: 'Sojasprossen', amount: '1', unit: 'Handvoll', pantry_basic: false },
      { name: 'Minze, Koriander, Thai-Basilikum', amount: '', unit: '', pantry_basic: false },
      { name: 'Geröstete Erdnüsse', amount: '1', unit: 'Handvoll', pantry_basic: true },
      { name: 'Zitronengras', amount: '2', unit: 'Stangen', pantry_basic: true },
      { name: 'Fischsauce, Sojasauce, Zucker, Limettensaft, Knoblauch, Chili', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Marinade: Knoblauch + Zitronengras (ganz fein) + Fischsauce + Sojasauce + Zucker + Öl. Rindfleisch (in Streifen) mind. 15 min drin ziehen lassen.',
      'Reisnudeln nach Packung (meist 3–5 min in heißem Wasser), kalt abschrecken.',
      'Nuoc Cham: 4 EL Fischsauce + 4 EL Wasser + 3 EL Zucker + 3 EL Limettensaft + Knoblauch + Chili verrühren.',
      'Pfanne sehr heiß, Rindfleisch in Portionen 1–2 min scharf anbraten (nicht zerkochen).',
      'In Schüsseln schichten: Salat unten, Nudeln, Karotte (Julienne), Gurke (Julienne), Sprossen, Rindfleisch obendrauf. Kräuter + Erdnüsse.',
      'Nuoc Cham drüber – jeder nach Geschmack.',
    ],
    notes: 'Bun Cha (Hanoi-Version) ist mit gegrilltem Schweinefleisch vom BGE – auch super.\n\nValerie: Nudeln + Rindfleisch (nur mit Salz gebraten, nicht aus Marinade) pur. Karotte + Gurke separat. Kein Nuoc Cham – milde Sojasauce.',
  },

  {
    id: 'gemuese-ofen-gratin',
    name: 'Gemüse-Ofen-Gratin',
    category: 'mealprep',
    cuisine: 'mediterran',
    time_min: 55,
    portions: 4,
    valerie_tauglich: true,
    device: ['ofen'],
    seasonal: null,
    ingredients: [
      { name: 'Kartoffeln (festkochend)', amount: '4', unit: 'Stück', pantry_basic: false },
      { name: 'Zucchini', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Tomaten', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Zwiebel', amount: '1', unit: 'Stück', pantry_basic: true },
      { name: 'Knoblauch', amount: '3', unit: 'Zehen', pantry_basic: true },
      { name: 'Sahne', amount: '200', unit: 'ml', pantry_basic: false },
      { name: 'Milch', amount: '100', unit: 'ml', pantry_basic: false },
      { name: 'Parmesan oder Gruyère', amount: '100', unit: 'g', pantry_basic: true },
      { name: 'Thymian, Rosmarin', amount: '', unit: '', pantry_basic: true },
      { name: 'Olivenöl, Salz, Pfeffer', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Ofen 190°C vorheizen. Auflaufform mit Olivenöl einreiben.',
      'Kartoffel-, Zucchini-, Tomaten-, Zwiebel-Scheiben in Schichten dachziegelartig einlegen. Zwischendurch salzen, pfeffern, Kräuter + Knoblauch streuen.',
      'Sahne + Milch verrühren, drübergießen.',
      'Parmesan/Gruyère drauf.',
      '35 min backen – obenauf goldbraun, Kartoffeln weich.',
    ],
    notes: 'Geht auch mit Süßkartoffel statt normaler Kartoffel + Feta statt Parmesan.\n\nValerie: Liebt das wie es ist. Ihre Portion extra lang ziehen lassen damit Kartoffeln wirklich weich sind. Weniger Knoblauch in ihrer Ecke.',
  },

  /* ═══════════════════════ WOCHENENDE ═══════════════════════ */

  {
    id: 'pho-bo',
    name: 'Pho Bo',
    category: 'wochenende',
    cuisine: 'vietnamesisch',
    time_min: 240,
    portions: 6,
    valerie_tauglich: true,
    device: ['topf'],
    seasonal: null,
    ingredients: [
      { name: 'Rinderknochen', amount: '1500', unit: 'g', pantry_basic: false },
      { name: 'Rinderbrust', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Zwiebeln', amount: '2', unit: 'Stück', pantry_basic: true },
      { name: 'Ingwer', amount: '10', unit: 'cm', pantry_basic: true },
      { name: 'Sternanis, Zimtstange, Nelken, Kardamom, Koriandersamen, Fenchelsamen', amount: '', unit: '', pantry_basic: true },
      { name: 'Fischsauce', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Zucker', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Reisnudeln (flach, Pho-Style)', amount: '400', unit: 'g', pantry_basic: true },
      { name: 'Rindfiletspitzen (hauchdünn)', amount: '300', unit: 'g', pantry_basic: false },
      { name: 'Thai-Basilikum, Koriander, Minze', amount: '', unit: '', pantry_basic: false },
      { name: 'Sojasprossen, Limette, Chili, Lauchzwiebel', amount: '', unit: '', pantry_basic: false },
      { name: 'Hoisin-Sauce, Sriracha', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Knochen + Brust in kaltem Wasser aufkochen, 10 min abschäumen, Wasser wegschütten, Fleisch abspülen. (Entfernt Trübstoffe – wichtig für klare Brühe!)',
      'Zwiebel + Ingwer trocken in der Pfanne schwarz anrösten. Gibt den Geschmack.',
      'Gewürze 2 min trocken in der Pfanne rösten.',
      'Knochen, Fleisch, Zwiebel, Ingwer, Gewürze (in Tuch) in großen Topf mit 4 L Wasser. Aufkochen, dann 3h bei kleinster Flamme simmern.',
      'Brust nach 1,5h rausnehmen, in dünne Scheiben schneiden.',
      'Brühe abseihen. Fischsauce + Zucker + Salz abschmecken.',
      'Nudeln nach Packung kochen.',
      'In Schalen: Nudeln unten, rohe Rindfleischscheiben + gekochte Brust obendrauf. Kochende Brühe drübergießen (gart rohes Fleisch). Kräuter, Sprossen, Limette, Chili.',
    ],
    notes: 'Brühe in großer Menge machen und in 500ml-Portionen einfrieren – dann ist Pho ein 15-Min-Gericht. Classic Wochenend-Investment.\n\nValerie: Brühe + Nudeln + gekochte Rinderbrust pur. Sojasauce zum Tunken. Sie mag Nudelsuppe.',
  },

  {
    id: 'pulled-pork-bge',
    name: 'Pulled Pork (Big Green Egg)',
    category: 'grill',
    cuisine: 'amerikanisch',
    time_min: 600,
    portions: 10,
    valerie_tauglich: true,
    device: ['bge'],
    seasonal: null,
    ingredients: [
      { name: 'Schweinenacken (mit Fettkappe)', amount: '2500', unit: 'g', pantry_basic: false },
      { name: 'Hickory- oder Apfelholz', amount: '', unit: '', pantry_basic: false },
      { name: 'Brauner Zucker', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Paprika edelsüß', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Meersalz', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Schwarzer Pfeffer, Knoblauchpulver, Zwiebelpulver, Senfpulver', amount: '', unit: 'je 1 EL', pantry_basic: true },
      { name: 'Cayenne + Kreuzkümmel', amount: '', unit: 'je 1 TL', pantry_basic: true },
      { name: 'Apfelsaft + Apfelessig', amount: '300', unit: 'ml (Mop)', pantry_basic: false },
      { name: 'Burger Buns oder Wraps', amount: '', unit: '', pantry_basic: false },
      { name: 'Rotkohl + Karotte + Mayo (Slaw)', amount: '', unit: '', pantry_basic: false },
      { name: 'BBQ-Sauce', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Rub (alle Gewürze mischen) gut einmassieren. Am Vorabend ideal, mind. 1h im Kühlschrank.',
      'BGE auf 110°C indirekt einregeln, Deflector einlegen, 2–3 Hickory-Stücke rein.',
      'Fleisch auf den Rost, Temperaturfühler rein. Ziel-Kerntemperatur: 93°C.',
      'Nach 4h Mop Sauce (Apfelsaft + Apfelessig + 1 EL Rub) alle Stunde auftragen.',
      'Bei 70°C Kerntemperatur "Stall" – kann 1–2h stehen (normal!). Eventuell Texas Crutch: in Alufolie wickeln.',
      'Bei 93°C fertig. 30 min in Folie ruhen lassen.',
      'Mit zwei Gabeln zerrupfen ("pullen"). Mit BBQ-Sauce vermischen.',
      'Auf Buns mit Slaw servieren.',
    ],
    notes: '8–10 Portionen! 2 für heute, 4 in den Freezer als Cubes (für Quesadillas, Wraps, über Reis). Ultimative Freezer-Held.\n\nValerie: Fleisch vor dem Mischen mit BBQ-Sauce abzweigen. Bun + Pulled Pork pur + Apfelstücke. Sie liebt das.',
  },

  {
    id: 'rotisserie-huhn-bge',
    name: 'Rotisserie-Hähnchen (Big Green Egg)',
    category: 'grill',
    cuisine: 'mediterran',
    time_min: 90,
    portions: 3,
    valerie_tauglich: true,
    device: ['bge'],
    seasonal: null,
    ingredients: [
      { name: 'Ganzes Bio-Hähnchen', amount: '1800', unit: 'g', pantry_basic: false },
      { name: 'Zitronen', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Knoblauchknolle', amount: '1', unit: 'Stück', pantry_basic: true },
      { name: 'Thymian, Rosmarin', amount: '', unit: 'frisch', pantry_basic: false },
      { name: 'Butter (weich)', amount: '50', unit: 'g', pantry_basic: true },
      { name: 'Salz, Pfeffer, Paprika edelsüß', amount: '', unit: '', pantry_basic: true },
      { name: 'Olivenöl + Küchengarn', amount: '', unit: '', pantry_basic: true },
      { name: 'Kartoffeln (Spalten)', amount: '', unit: 'als Beilage', pantry_basic: false },
    ],
    steps: [
      'Hähnchen innen + außen trocken tupfen. Salzen, pfeffern (auch innen).',
      'Kräuterbutter: Butter + Thymian + Rosmarin + Knoblauch + Paprika verrühren. Unter die Haut der Brust schieben.',
      'Innen: halbierte Zitrone + Knoblauchknolle reinstopfen.',
      'Mit Küchengarn verschnüren (Beine zusammen, Flügel anlegen).',
      'BGE auf 180°C indirekt. Hähnchen auf Rotisserie-Spieß, einspannen.',
      '1h 15 min rotieren lassen (bis Brust 75°C Kerntemperatur).',
      '10 min ruhen lassen, tranchieren.',
    ],
    notes: 'Reste-Magie: morgen als Wraps, übermorgen als Huhn-Nudel-Suppe mit Karkasse-Brühe. 3 Mahlzeiten aus einem Huhn.\n\nValerie: Liebt gegrilltes Huhn – Brust ohne Haut, kleingeschnitten, mit Kartoffelspalten. Keine Anpassung nötig.',
  },

  {
    id: 'boeuf-bourguignon',
    name: 'Boeuf Bourguignon (Dutch Oven)',
    category: 'wochenende',
    cuisine: 'franzoesisch',
    time_min: 180,
    portions: 6,
    valerie_tauglich: true,
    device: ['dutch_oven'],
    seasonal: null,
    ingredients: [
      { name: 'Rindfleisch aus der Schulter (4 cm Würfel)', amount: '1500', unit: 'g', pantry_basic: false },
      { name: 'Speck', amount: '150', unit: 'g', pantry_basic: false },
      { name: 'Zwiebeln', amount: '2', unit: 'Stück', pantry_basic: true },
      { name: 'Karotten', amount: '3', unit: 'Stück', pantry_basic: false },
      { name: 'Knoblauch', amount: '4', unit: 'Zehen', pantry_basic: true },
      { name: 'Mehl', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Burgunderwein (oder guter Rotwein)', amount: '750', unit: 'ml', pantry_basic: false },
      { name: 'Rinderbrühe', amount: '500', unit: 'ml', pantry_basic: true },
      { name: 'Tomatenmark', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Bouquet garni (Thymian, Rosmarin, Lorbeer, Petersilie)', amount: '1', unit: 'Stück', pantry_basic: true },
      { name: 'Perlzwiebeln (oder Schalotten)', amount: '250', unit: 'g', pantry_basic: false },
      { name: 'Champignons', amount: '300', unit: 'g', pantry_basic: false },
      { name: 'Butter, Salz, Pfeffer', amount: '', unit: '', pantry_basic: true },
      { name: 'Kartoffelpüree oder Baguette', amount: '', unit: 'als Beilage', pantry_basic: false },
    ],
    steps: [
      'Ofen auf 160°C vorheizen.',
      'Im Dutch Oven Speck kross braten, rausnehmen.',
      'Rindfleisch trocken tupfen, in Portionen scharf anbraten bis braun. NICHT zerkochen! Rausnehmen.',
      'Zwiebeln + Karotten 5 min anbraten. Knoblauch + Tomatenmark, 1 min.',
      'Mehl drüberstäuben, kurz mitrösten.',
      'Wein + Brühe langsam unter Rühren. Fleisch + Speck zurück, Bouquet garni rein.',
      'Aufkochen, Deckel drauf, 2,5h in den Ofen.',
      'In letzter halber Stunde: Perlzwiebeln + Champignons (geviertelt) in Butter anbraten und dazugeben.',
      'Bouquet garni raus. Salz, Pfeffer. Mit Kartoffelpüree oder Baguette servieren.',
    ],
    notes: 'Am nächsten Tag schmeckt\'s noch besser. Perfektes Gericht wenn Besuch kommt.\n\nValerie: Rindfleischwürfel + Karotten aus dem Topf fischen, ohne Weinsauce, zu Kartoffelpüree. Sie isst überraschend gern Schmorfleisch.',
  },

  {
    id: 'moussaka',
    name: 'Moussaka mit Béchamel',
    category: 'wochenende',
    cuisine: 'griechisch',
    time_min: 90,
    portions: 6,
    valerie_tauglich: true,
    device: ['ofen', 'pfanne'],
    seasonal: null,
    ingredients: [
      { name: 'Auberginen (in Scheiben, 1 cm)', amount: '3', unit: 'Stück', pantry_basic: false },
      { name: 'Kartoffeln (in Scheiben)', amount: '3', unit: 'Stück', pantry_basic: false },
      { name: 'Lammhack (oder gemischt)', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Zwiebeln', amount: '2', unit: 'Stück', pantry_basic: true },
      { name: 'Knoblauch', amount: '4', unit: 'Zehen', pantry_basic: true },
      { name: 'Dosentomaten', amount: '400', unit: 'g', pantry_basic: true },
      { name: 'Rotwein', amount: '200', unit: 'ml', pantry_basic: false },
      { name: 'Tomatenmark', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Zimt + Piment + Lorbeer', amount: '', unit: '', pantry_basic: true },
      { name: 'Butter (Béchamel)', amount: '70', unit: 'g', pantry_basic: true },
      { name: 'Mehl (Béchamel)', amount: '70', unit: 'g', pantry_basic: true },
      { name: 'Milch warm (Béchamel)', amount: '700', unit: 'ml', pantry_basic: true },
      { name: 'Kefalotyri oder Parmesan', amount: '100', unit: 'g', pantry_basic: true },
      { name: 'Eigelb', amount: '2', unit: 'Stück', pantry_basic: true },
      { name: 'Muskat, Salz, Olivenöl', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Ofen 200°C vorheizen. Auberginen + Kartoffeln auf Blech, mit Öl bestreichen, salzen. 25 min vorbacken (Auberginen 15 min, weil weicher).',
      'Fleisch-Sauce: Zwiebeln anbraten, Hack krümelig braten. Knoblauch + Tomatenmark + Gewürze. Wein dazu, reduzieren. Dosentomaten, 25 min simmern bis dick.',
      'Béchamel: Butter schmelzen, Mehl 1 min mitrösten (Mehlschwitze). Milch langsam einrühren (ständig schlagen!). 5 min köcheln bis dick. Käse + Muskat. Vom Herd, Eigelb einrühren.',
      'Schichten: Kartoffeln → Auberginen → Fleischsauce → Auberginen → Béchamel obendrauf.',
      'Nochmal Käse drüber, 45 min bei 180°C backen bis goldbraun. 15 min ruhen lassen vor dem Servieren.',
    ],
    notes: 'Moussaka braucht Ruhe zum Schneiden – sonst fällt sie auseinander. Am nächsten Tag noch besser.\n\nValerie: Liebt Moussaka genauso wie sie ist. Kleinere Portion, gut abkühlen lassen.',
  },

  {
    id: 'ramen-shoyu',
    name: 'Ramen from Scratch (Shoyu-Basis)',
    category: 'wochenende',
    cuisine: 'japanisch',
    time_min: 150,
    portions: 4,
    valerie_tauglich: true,
    device: ['topf'],
    seasonal: null,
    ingredients: [
      { name: 'Hähnchenknochen (oder Flügel)', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Rinderknochen (optional)', amount: '200', unit: 'g', pantry_basic: false },
      { name: 'Kombu (getrocknete Alge)', amount: '10', unit: 'cm Stück', pantry_basic: true },
      { name: 'Bonito-Flocken (Katsuobushi)', amount: '30', unit: 'g', pantry_basic: true },
      { name: 'Lauchzwiebeln, Ingwer, Knoblauch, Zwiebel (Brühe)', amount: '', unit: '', pantry_basic: true },
      { name: 'Sojasauce (gute Qualität)', amount: '100', unit: 'ml', pantry_basic: true },
      { name: 'Mirin', amount: '50', unit: 'ml', pantry_basic: true },
      { name: 'Zucker', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Ramen-Nudeln (frisch, Asialaden)', amount: '4', unit: 'Portionen', pantry_basic: false },
      { name: 'Eier (Ajitsuke Tamago)', amount: '4', unit: 'Stück', pantry_basic: true },
      { name: 'Chashu oder Rotisserie-Hähnchen-Reste', amount: '200', unit: 'g', pantry_basic: false },
      { name: 'Nori-Blätter, Bambussprossen, Sesam', amount: '', unit: '', pantry_basic: true },
      { name: 'Chili-Öl (Rayu, optional)', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Brühe starten: Knochen in kaltem Wasser aufkochen, 5 min abschäumen, abgießen, Knochen abspülen. (Reinigungsschritt – wichtig!)',
      'Knochen + 2 L frisches Wasser + Ingwer + Knoblauch + Zwiebel + Lauchzwiebel + Kombu aufkochen.',
      '1,5h bei kleinster Flamme simmern. Kombu nach 30 min rausnehmen (wird sonst bitter).',
      'Letzte 15 min: Katsuobushi reinwerfen. 5 min ziehen lassen. Durch feines Sieb abseihen. Salzen.',
      'Tare: Sojasauce + Mirin + Zucker + Knoblauch + Ingwer 5 min köcheln, abseihen.',
      'Ajitsuke Tamago: Eier 6 min kochen, pellen, über Nacht in Sojasauce + Mirin + Wasser (je 100 ml) einlegen.',
      'Anrichten: 3 EL Tare in jede Schüssel. Kochend heiße Brühe drübergießen (ca. 350 ml pro Schale).',
      'Nudeln separat kochen, abgießen, in die Brühe. Toppings drauf: Chashu-Scheiben, Ei-Hälfte, Lauchzwiebel, Nori, Bambus, Sesam, Chili-Öl.',
    ],
    notes: 'Projekt-Rezept. Brühe in großer Menge machen und in 500ml-Portionen einfrieren. Dann sind spätere Ramen ein 20-Min-Gericht. Shoyu ist die zugänglichste Ramen-Variante.\n\nValerie: Nudeln + klare Brühe + Hähnchenstücke + Ei – ohne Tare (Sojasauce separat zum Tunken). Sie liebt die Nudeln.',
  },
]

// Mark all as seed for future migration
const STAMPED_SEEDS = SEED_RECIPES.map((r) => ({
  ...r,
  seed: true,
  favorite: false,
  times_cooked: 0,
  created_at: now(),
}))

/**
 * Idempotent seed with migration.
 *   version 0 → no seed yet          → insert all
 *   version 1 → old 10-recipe seed   → delete all seed:true, insert new
 *   version 2 → current (this)       → no-op
 * User-created recipes (seed flag missing/false) are never touched.
 */
export async function seedIfEmpty() {
  const setting = await db.settings.get('seedVersion')
  const currentVersion = setting?.value ?? 0
  if (currentVersion >= SEED_VERSION) return false

  // Wipe old seeds (legacy recipes without seed flag but with known slugs from v1)
  const LEGACY_IDS = [
    'bolognese-ragu', 'thai-curry-huhn', 'linsen-dal', 'spargel-risotto',
    'shakshuka', 'moussaka', 'aglio-e-olio', 'rotisserie-huhn-bge',
    'overnight-oats', 'baerlauch-pesto',
  ]
  await db.transaction('rw', db.recipes, db.settings, async () => {
    const allRecipes = await db.recipes.toArray()
    const toDelete = allRecipes
      .filter((r) => r.seed === true || LEGACY_IDS.includes(r.id))
      .map((r) => r.id)
    if (toDelete.length) await db.recipes.bulkDelete(toDelete)
    await db.recipes.bulkPut(STAMPED_SEEDS)
    await db.settings.put({ key: 'seedVersion', value: SEED_VERSION })
  })
  return true
}
