import { db } from './schema'

const now = () => new Date().toISOString()

const SEED_RECIPES = [
  {
    id: 'bolognese-ragu',
    name: 'Bolognese Ragù',
    category: 'mealprep',
    cuisine: 'italienisch',
    time_min: 90,
    portions: 6,
    valerie_tauglich: true,
    device: ['thermomix'],
    seasonal: null,
    ingredients: [
      { name: 'Karotte', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Sellerie', amount: '1', unit: 'Stange', pantry_basic: false },
      { name: 'Zwiebel', amount: '1', unit: 'Stück', pantry_basic: true },
      { name: 'Knoblauch', amount: '2', unit: 'Zehen', pantry_basic: true },
      { name: 'Olivenöl', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Rinderhack (mit etwas Schwein)', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Rotwein', amount: '150', unit: 'ml', pantry_basic: false },
      { name: 'Passata', amount: '400', unit: 'g', pantry_basic: false },
      { name: 'Tomatenmark', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Milch (Vollfett)', amount: '150', unit: 'ml', pantry_basic: false },
      { name: 'Lorbeerblatt', amount: '1', unit: 'Stück', pantry_basic: true },
      { name: 'Muskatnuss', amount: '1', unit: 'Prise', pantry_basic: true },
      { name: 'Salz, Pfeffer', amount: '', unit: 'nach Geschmack', pantry_basic: true },
    ],
    steps: [
      'Karotte, Sellerie, Zwiebel und Knoblauch grob stückeln und in den Mixtopf geben. 5 Sek / Stufe 5 zerkleinern.',
      'Olivenöl dazugeben. 5 Min / 120°C / Stufe 1 anschwitzen (Messbecher offen).',
      'Hackfleisch dazugeben. 8 Min / 120°C / Linkslauf / Stufe 1 anbraten, bis die Feuchtigkeit weitestgehend verdunstet ist.',
      'Mit Rotwein ablöschen. 3 Min / 100°C / Linkslauf / Stufe 1 einreduzieren lassen.',
      'Passata, Tomatenmark, Milch, Lorbeer, Muskat, Salz und Pfeffer dazu. 60 Min / 95°C / Linkslauf / Stufe Sanft köcheln, Messbecher schräg auflegen.',
      'Lorbeer raus, abschmecken. Heiß über frische Pasta oder in Eiswürfelformen als Cubes einfrieren.',
    ],
    notes: 'Hält gekühlt 3 Tage. Cubes einfrieren für Schnell-Pasta unter der Woche. Für Valerie ohne Pfeffer abzweigen.',
    favorite: true,
    times_cooked: 0,
    created_at: now(),
  },
  {
    id: 'thai-curry-huhn',
    name: 'Rotes Thai-Curry mit Hähnchen',
    category: 'mealprep',
    cuisine: 'asiatisch',
    time_min: 35,
    portions: 4,
    valerie_tauglich: false,
    device: ['thermomix'],
    seasonal: null,
    ingredients: [
      { name: 'Hähnchenbrust', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Rote Currypaste (Maesri)', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Kokosmilch', amount: '800', unit: 'ml', pantry_basic: true },
      { name: 'Paprika rot', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Zuckerschoten', amount: '200', unit: 'g', pantry_basic: false },
      { name: 'Bambussprossen', amount: '200', unit: 'g (Dose)', pantry_basic: true },
      { name: 'Kaffir-Limettenblätter', amount: '4', unit: 'Stück', pantry_basic: true },
      { name: 'Fischsauce', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Palmzucker (oder brauner Zucker)', amount: '1', unit: 'EL', pantry_basic: true },
      { name: 'Limettensaft', amount: '1', unit: 'EL', pantry_basic: false },
      { name: 'Thai-Basilikum', amount: '1', unit: 'Handvoll', pantry_basic: false },
      { name: 'Jasmin-Reis (als Beilage)', amount: '300', unit: 'g', pantry_basic: true },
    ],
    steps: [
      'Hähnchen in mundgerechte Stücke schneiden. Paprika in Streifen, Zuckerschoten halbieren.',
      'Currypaste mit 2 EL Kokosmilch in den Mixtopf. 4 Min / 120°C / Stufe 1 anrösten bis es duftet.',
      'Restliche Kokosmilch, Limettenblätter, Fischsauce, Zucker dazu. Hähnchen einlegen. 12 Min / 95°C / Linkslauf / Stufe Sanft.',
      'Paprika und Zuckerschoten dazu. 5 Min / 95°C / Linkslauf / Stufe Sanft. Bambus in den letzten 2 Minuten.',
      'Limettensaft einrühren, Thai-Basilikum drüberzupfen. Mit Jasmin-Reis servieren.',
    ],
    notes: 'Currypaste-Menge nach Geschmack anpassen. Mila findet Maesri mit Abstand die beste. Reste halten 3 Tage, Schärfe wird intensiver.',
    favorite: true,
    times_cooked: 0,
    created_at: now(),
  },
  {
    id: 'linsen-dal',
    name: 'Linsen-Dal mit Kokosmilch',
    category: 'mealprep',
    cuisine: 'levante',
    time_min: 35,
    portions: 4,
    valerie_tauglich: true,
    device: ['thermomix'],
    seasonal: null,
    ingredients: [
      { name: 'Rote Linsen', amount: '250', unit: 'g', pantry_basic: true },
      { name: 'Zwiebel', amount: '1', unit: 'Stück', pantry_basic: true },
      { name: 'Knoblauch', amount: '2', unit: 'Zehen', pantry_basic: true },
      { name: 'Ingwer frisch', amount: '20', unit: 'g', pantry_basic: false },
      { name: 'Kurkuma', amount: '1', unit: 'TL', pantry_basic: true },
      { name: 'Kreuzkümmel (Kumin)', amount: '1', unit: 'TL', pantry_basic: true },
      { name: 'Garam Masala', amount: '1', unit: 'TL', pantry_basic: true },
      { name: 'Kokosmilch', amount: '400', unit: 'ml', pantry_basic: true },
      { name: 'Gehackte Tomaten', amount: '400', unit: 'g (Dose)', pantry_basic: true },
      { name: 'Gemüsebrühe', amount: '300', unit: 'ml', pantry_basic: true },
      { name: 'Koriander frisch', amount: '1/2', unit: 'Bund', pantry_basic: false },
      { name: 'Salz', amount: '', unit: 'nach Geschmack', pantry_basic: true },
    ],
    steps: [
      'Zwiebel, Knoblauch, Ingwer in den Mixtopf. 3 Sek / Stufe 7 zerkleinern.',
      '1 EL Öl dazu. 3 Min / 120°C / Stufe 1 anschwitzen.',
      'Gewürze dazu. 1 Min / 120°C / Stufe 1 rösten (für Valerie milder dosieren).',
      'Linsen, Tomaten, Kokosmilch, Brühe dazu. 20 Min / 100°C / Linkslauf / Stufe Sanft köcheln.',
      'Abschmecken, mit Koriander bestreuen. Dazu passt Basmati-Reis oder Naan.',
    ],
    notes: 'Valerie-Version: weniger Garam Masala, kein Kreuzkümmel im Ganzen. Cubes super einfrierbar.',
    favorite: false,
    times_cooked: 0,
    created_at: now(),
  },
  {
    id: 'spargel-risotto',
    name: 'Spargel-Risotto',
    category: 'wochenende',
    cuisine: 'italienisch',
    time_min: 40,
    portions: 4,
    valerie_tauglich: true,
    device: ['thermomix'],
    seasonal: { start: 4, end: 6 },
    ingredients: [
      { name: 'Risotto-Reis (Carnaroli)', amount: '320', unit: 'g', pantry_basic: true },
      { name: 'Weißer Spargel', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Schalotte', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Weißwein trocken', amount: '100', unit: 'ml', pantry_basic: false },
      { name: 'Gemüsebrühe heiß', amount: '900', unit: 'ml', pantry_basic: true },
      { name: 'Butter', amount: '50', unit: 'g', pantry_basic: true },
      { name: 'Parmesan (frisch gerieben)', amount: '60', unit: 'g', pantry_basic: true },
      { name: 'Zitronenzeste (unbehandelt)', amount: '1/2', unit: 'Zitrone', pantry_basic: false },
      { name: 'Salz', amount: '', unit: 'nach Geschmack', pantry_basic: true },
    ],
    steps: [
      'Spargel schälen, holzige Enden entfernen. Köpfe 4 cm abschneiden und beiseite. Rest in 1 cm Stücke.',
      'Schalotte zerkleinern (3 Sek / Stufe 6). Butter dazu, 3 Min / 120°C / Stufe 1 anschwitzen.',
      'Reis dazu, 2 Min / 120°C / Linkslauf / Stufe 1 anrösten. Wein, dann Spargelstücke (ohne Köpfe) dazu.',
      'Heiße Brühe dazugeben. 15 Min / 100°C / Linkslauf / Stufe Sanft, in den letzten 4 Min Spargelköpfe dazu.',
      'Parmesan und Zitronenzeste unterrühren, 2 Min ruhen lassen. Butter-käsig abschmecken.',
    ],
    notes: 'Saisonal April-Juni. Grüner Spargel auch gut. Valerie liebt das creamy, dann Parmesan großzügig.',
    favorite: false,
    times_cooked: 0,
    created_at: now(),
  },
  {
    id: 'shakshuka',
    name: 'Shakshuka',
    category: 'schnell',
    cuisine: 'levante',
    time_min: 25,
    portions: 2,
    valerie_tauglich: true,
    device: ['pfanne'],
    seasonal: null,
    ingredients: [
      { name: 'Eier', amount: '4', unit: 'Stück', pantry_basic: true },
      { name: 'Paprika rot', amount: '1', unit: 'Stück', pantry_basic: false },
      { name: 'Zwiebel', amount: '1', unit: 'Stück', pantry_basic: true },
      { name: 'Knoblauch', amount: '2', unit: 'Zehen', pantry_basic: true },
      { name: 'Passata', amount: '400', unit: 'g', pantry_basic: true },
      { name: 'Kreuzkümmel', amount: '1', unit: 'TL', pantry_basic: true },
      { name: 'Paprikapulver edelsüß', amount: '1', unit: 'TL', pantry_basic: true },
      { name: 'Feta', amount: '80', unit: 'g', pantry_basic: false },
      { name: 'Koriander oder Petersilie', amount: '1/2', unit: 'Bund', pantry_basic: false },
      { name: 'Olivenöl, Salz, Pfeffer', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Paprika und Zwiebel in Streifen, Knoblauch fein. In großer Pfanne mit Olivenöl 6 Min anschwitzen.',
      'Gewürze zugeben, 30 Sek mitrösten. Passata angießen, mit Salz und Pfeffer abschmecken.',
      '8 Min simmern lassen bis die Sauce etwas eingedickt ist.',
      '4 Mulden formen, Eier hineinschlagen. Deckel drauf, 5–7 Min bei mittlerer Hitze bis Eiweiß gestockt aber Eigelb noch flüssig.',
      'Feta darüber krümeln, Kräuter drauf. Mit Fladenbrot servieren.',
    ],
    notes: 'Valerie: ein Ei im Ganzen, Gewürze milder. Klassisches Sonntags-Frühstück.',
    favorite: false,
    times_cooked: 0,
    created_at: now(),
  },
  {
    id: 'moussaka',
    name: 'Moussaka',
    category: 'wochenende',
    cuisine: 'mediterran',
    time_min: 120,
    portions: 6,
    valerie_tauglich: true,
    device: ['ofen'],
    seasonal: null,
    ingredients: [
      { name: 'Auberginen', amount: '2', unit: 'große', pantry_basic: false },
      { name: 'Kartoffeln festkochend', amount: '500', unit: 'g', pantry_basic: false },
      { name: 'Lammhack (oder Rind)', amount: '600', unit: 'g', pantry_basic: false },
      { name: 'Zwiebel', amount: '2', unit: 'Stück', pantry_basic: true },
      { name: 'Knoblauch', amount: '3', unit: 'Zehen', pantry_basic: true },
      { name: 'Passata', amount: '400', unit: 'g', pantry_basic: true },
      { name: 'Rotwein', amount: '100', unit: 'ml', pantry_basic: false },
      { name: 'Zimt', amount: '1/2', unit: 'TL', pantry_basic: true },
      { name: 'Butter', amount: '50', unit: 'g (für Bechamel)', pantry_basic: true },
      { name: 'Mehl', amount: '50', unit: 'g (für Bechamel)', pantry_basic: true },
      { name: 'Milch', amount: '600', unit: 'ml (für Bechamel)', pantry_basic: true },
      { name: 'Muskat, Salz, Pfeffer', amount: '', unit: '', pantry_basic: true },
      { name: 'Parmesan gerieben', amount: '50', unit: 'g', pantry_basic: true },
      { name: 'Olivenöl', amount: '5', unit: 'EL', pantry_basic: true },
    ],
    steps: [
      'Auberginen in 1 cm Scheiben, salzen, 15 Min ziehen lassen, abspülen, trocken tupfen. Kartoffeln in 5 mm Scheiben.',
      'Auberginen und Kartoffeln mit Olivenöl bestreichen, bei 200°C Ober-/Unterhitze 15 Min vorbacken.',
      'Parallel Fleischragù: Zwiebel + Knoblauch anschwitzen, Hack anbraten, Rotwein, Passata, Zimt, 20 Min simmern.',
      'Bechamel: Butter schmelzen, Mehl einrühren, Milch langsam angießen, aufkochen bis sämig, Muskat.',
      'Auflaufform schichten: Kartoffeln unten, dann Aubergine, dann Ragù, nochmal Aubergine, Bechamel drüber, Parmesan.',
      'Bei 180°C 40 Min backen bis goldbraun. 15 Min ruhen lassen, dann schneiden.',
    ],
    notes: 'Sonntagsessen. Schmeckt am nächsten Tag noch besser. Reste halten 4 Tage.',
    favorite: false,
    times_cooked: 0,
    created_at: now(),
  },
  {
    id: 'aglio-e-olio',
    name: 'Aglio e Olio',
    category: 'schnell',
    cuisine: 'italienisch',
    time_min: 15,
    portions: 2,
    valerie_tauglich: true,
    device: ['pfanne'],
    seasonal: null,
    ingredients: [
      { name: 'Spaghetti', amount: '200', unit: 'g', pantry_basic: true },
      { name: 'Knoblauch', amount: '4', unit: 'Zehen', pantry_basic: true },
      { name: 'Olivenöl extra vergine', amount: '5', unit: 'EL', pantry_basic: true },
      { name: 'Peperoncino (oder Chiliflocken)', amount: '1/2', unit: 'TL', pantry_basic: true },
      { name: 'Petersilie glatt', amount: '1/2', unit: 'Bund', pantry_basic: false },
      { name: 'Meersalz', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Salzwasser zum Kochen bringen. Spaghetti "al dente minus 1 Min" kochen. 1 Tasse Pastawasser aufheben.',
      'Knoblauch in hauchdünne Scheiben. In großer Pfanne mit Olivenöl bei mittlerer Hitze langsam goldgelb ziehen (NICHT braun), Chili dazu.',
      'Pasta direkt in die Pfanne, 2 EL Pastawasser, kräftig schwenken bis eine Emulsion entsteht (1–2 Min).',
      'Petersilie drüber. Für Valerie Portion ohne Chili abzweigen.',
    ],
    notes: 'Der Trick: Pastawasser + ständiges Schwenken macht die cremige Emulsion. Kein Parmesan – das ist Römer-Kanon.',
    favorite: true,
    times_cooked: 0,
    created_at: now(),
  },
  {
    id: 'rotisserie-huhn-bge',
    name: 'Rotisserie-Hähnchen vom BGE',
    category: 'wochenende',
    cuisine: 'mediterran',
    time_min: 90,
    portions: 4,
    valerie_tauglich: true,
    device: ['bge'],
    seasonal: null,
    ingredients: [
      { name: 'Ganzes Hähnchen', amount: '1.5', unit: 'kg', pantry_basic: false },
      { name: 'Zitronen (Bio)', amount: '2', unit: 'Stück', pantry_basic: false },
      { name: 'Knoblauchknolle', amount: '1', unit: 'Stück', pantry_basic: true },
      { name: 'Rosmarin-Zweige', amount: '3', unit: 'Stück', pantry_basic: false },
      { name: 'Thymian-Zweige', amount: '5', unit: 'Stück', pantry_basic: false },
      { name: 'Olivenöl', amount: '3', unit: 'EL', pantry_basic: true },
      { name: 'Meersalz grob', amount: '', unit: '', pantry_basic: true },
      { name: 'Schwarzer Pfeffer', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'BGE auf 175°C indirekt einstellen (Plate Setter). Kirschholz oder Buchenchips für Rauchnote.',
      'Hähnchen trocken tupfen, innen und außen salzen. Mit Olivenöl einreiben, pfeffern.',
      'Zitronen halbieren, Knoblauchknolle halbieren, Kräuter in die Bauchhöhle stopfen. Flügel anlegen, Keulen binden.',
      'Auf den Rotisserie-Spieß, ca. 75 Min drehen bis Kerntemperatur 74°C an der Brust (Thermometer!).',
      '10 Min ruhen lassen, tranchieren. Knochen aufheben für Brühe (TM!).',
    ],
    notes: 'Reste am Montag in Sandwiches oder als Grundlage für Ramen-Brühe. Knochen einfrieren.',
    favorite: false,
    times_cooked: 0,
    created_at: now(),
  },
  {
    id: 'overnight-oats',
    name: 'Overnight Oats (Basis)',
    category: 'fruehstueck',
    cuisine: 'fusion',
    time_min: 5,
    portions: 2,
    valerie_tauglich: true,
    device: ['thermomix'],
    seasonal: null,
    ingredients: [
      { name: 'Haferflocken zart', amount: '120', unit: 'g', pantry_basic: true },
      { name: 'Hafermilch (oder Vollmilch)', amount: '300', unit: 'ml', pantry_basic: true },
      { name: 'Joghurt griechisch', amount: '4', unit: 'EL', pantry_basic: false },
      { name: 'Chiasamen', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Ahornsirup (oder Honig)', amount: '2', unit: 'EL', pantry_basic: true },
      { name: 'Zimt', amount: '1/2', unit: 'TL', pantry_basic: true },
      { name: 'Topping: Beeren, Banane, Nüsse', amount: '', unit: 'nach Wahl', pantry_basic: false },
      { name: 'Prise Salz', amount: '', unit: '', pantry_basic: true },
    ],
    steps: [
      'Alles außer Topping in 2 Gläsern oder einer Schüssel verrühren.',
      'Über Nacht (mind. 6 h) im Kühlschrank quellen lassen.',
      'Am Morgen Topping drauf, ggf. mit Milch lockern.',
    ],
    notes: 'Annas Favorit. Kann 3 Tage vorbereiten. Valerie liebt mit Banane und Beeren.',
    favorite: true,
    times_cooked: 0,
    created_at: now(),
  },
  {
    id: 'baerlauch-pesto',
    name: 'Bärlauch-Pesto',
    category: 'mealprep',
    cuisine: 'italienisch',
    time_min: 15,
    portions: 6,
    valerie_tauglich: true,
    device: ['thermomix'],
    seasonal: { start: 4, end: 5 },
    ingredients: [
      { name: 'Bärlauch frisch', amount: '100', unit: 'g (ca. 2 Handvoll)', pantry_basic: false },
      { name: 'Pinienkerne geröstet', amount: '40', unit: 'g', pantry_basic: true },
      { name: 'Parmesan (frisch gerieben)', amount: '50', unit: 'g', pantry_basic: true },
      { name: 'Olivenöl extra vergine', amount: '120', unit: 'ml', pantry_basic: true },
      { name: 'Zitronensaft', amount: '1', unit: 'EL', pantry_basic: false },
      { name: 'Meersalz', amount: '', unit: 'nach Geschmack', pantry_basic: true },
    ],
    steps: [
      'Bärlauch waschen, trocken schleudern, grob schneiden.',
      'Pinienkerne trocken in Pfanne rösten bis goldbraun. Abkühlen lassen.',
      'Alles in den Mixtopf: 10 Sek / Stufe 7. Spateln, nochmal 5 Sek / Stufe 5. Abschmecken.',
      'In Eiswürfelformen füllen, einfrieren. Cubes in Zipbeutel umfüllen. Hält 6 Monate.',
    ],
    notes: 'Saisonal April-Mai. Ein Cube = eine Portion Pasta für 2. Perfekt als schneller Weekday-Move.',
    favorite: true,
    times_cooked: 0,
    created_at: now(),
  },
]

export async function seedIfEmpty() {
  const count = await db.recipes.count()
  if (count > 0) return false
  await db.recipes.bulkAdd(SEED_RECIPES)
  return true
}
